version: '3'
name: laravel-project

services:
    ####################################################################################################
    # Frontend
    ####################################################################################################
    # 1- docker build -t front ./frontend/.
    # 2- docker run -d -p 3000:3000 --name nextjs front
    frontend:
        build: ./frontend
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app
    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: ./docker/php
        # ports:
        #     - 5173:5173
        volumes:
            - ./backend:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./backend:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        image: mysql:8.1
        ports:
            - 3306:3306
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/logs:/var/log/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    # ####################################################################################################
    # # DATABASE (MariaDB)
    # ####################################################################################################
    # db:
    #     image: mariadb:10.11
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./docker/db/data:/var/lib/mysql
    #         - ./docker/logs:/var/log/mysql
    #         - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - ./docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: laravel_db_name
    #         MYSQL_USER: laravel_db_user
    #         MYSQL_PASSWORD: laravel_db_pass

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - ./docker/phpmyadmin/sessions:/sessions

    ####################################################################################################
    # MongoDB
    ####################################################################################################
    mongo:
      image: mongo:7.0
      restart: always
      ports:
        - "27027:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
